insert into countries(country) values ('Russia')
insert into countries(country) values ('Kazakhstan')
insert into countries(country) values ('Georgia')
insert into countries(country) values ('Ukraine')
insert into countries(country) values ('Latvia')

insert into cities(city, country_id) values ('Novosibirsk', 1)
insert into cities(city, country_id) values ('Moscow', 1)
insert into cities(city, country_id) values ('Omsk', 1)
insert into cities(city, country_id) values ('Almaty', 2)
insert into cities(city, country_id) values ('Tbilisi', 3)
insert into cities(city, country_id) values ('Batumi', 3)
insert into cities(city, country_id) values ('Kiev', 4)
insert into cities(city, country_id) values ('Odessa', 4)
insert into cities(city, country_id) values ('Riga', 5)

insert into services(name) values ('Services 1')
insert into services(name) values ('Services 2')
insert into services(name) values ('Services 3')
insert into services(name) values ('Services 4')